#include "AST/Base.h"

#include "AST/Assignment.h"
#include "AST/BinaryOperation.h"
#include "AST/FunctionCall.h"
#include "AST/Real.h"
#include "AST/Integer.h"
#include "AST/UnaryOperation.h"
#include "AST/VariableDefinition.h"
#include "AST/Base.h"
#include "AST/Compound.h"
#include "AST/FunctionDefinition.h"
#include "AST/ReturnStatement.h"
#include "AST/PrintStatement.h"
#include "AST/Variable.h"
#include "AST/String.h"
#include "AST/Character.h"
#include "AST/Boolean.h"
